packages:
  - apps/*
  - packages/*
catalog:
  '@types/node': '^22.15.3'
  '@types/react': '^19.1.0'
  '@types/react-dom': '^19.1.1'
  'eslint': '^9.34.0'
  'next': '^15.5.9'
  'react': '^19.1.2'
  'react-dom': '^19.1.0'
  'stylelint': '^16.25.0'
  'typescript': '^5.9.2'
ignoredBuiltDependencies:
  - sharp
  - unrs-resolver
